version: '3.0'
services:
  angular-service:
    container_name: angularcontainer
    build: ./
    volumes:
      - './:/usr/src/app'
    ports:
      - '8080:8080'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 8080"